version: '3'

services:
  mlmet:
    build: .
    image: mlmet:latest
    container_name: mlmet
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./data:/app/data  # 可选：映射数据目录
    network_mode: host
    ipc: host
    restart: unless-stopped